#
# TABLE STRUCTURE FOR: user
#

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` char(64) COLLATE utf8_unicode_ci NOT NULL,
  `username` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `location` char(5) COLLATE utf8_unicode_ci NOT NULL,
  `bio` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_photo` text COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (1, 'boyle.rick@example.org', '854878bd8fe9bf9a4ca49e18fe8f2df47b50f38c', 'frodriguez', '53936', 'Fugit excepturi et corporis autem possimus. Aut qui minima aliquam dicta eos. Est consequatur aut adipisci iure qui.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (2, 'tcrona@example.net', '79baad0f7eda4fec1e69429948147c92066c0b7c', 'joyce56', '77390', 'Doloremque libero illo itaque hic. Est velit est temporibus adipisci. Expedita ea numquam excepturi eum. A molestiae ut id.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (3, 'morissette.lucius@example.com', '768b48bcb448ed0d6e237371841303fde5e76fb8', 'clifford78', '37980', 'Et voluptas totam quam eos. At exercitationem possimus neque facere dolore vel sapiente. Esse asperiores aliquid hic.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (4, 'imogene.pouros@example.com', '1c77fce24bbb719718e082dff8157400759ab3cd', 'lera73', '09721', 'Ea magnam error deleniti exercitationem nesciunt illo. Sit sunt soluta sed. Omnis aut modi repellendus perferendis itaque.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (5, 'lrogahn@example.org', 'e62c16d3b5c0ef87bb430681c9c602d3143aa0af', 'schmidt.baylee', '16022', 'Libero illum ullam quaerat atque tempora. Quaerat numquam accusamus consequatur doloremque odit et vel. Rem et illo cum ipsum. Deleniti distinctio voluptatem assumenda consequatur.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (6, 'ruthe.huels@example.org', 'b7f9123970bb3cd3364bd60c66c43ab2dee6394f', 'beahan.waldo', '54538', 'Ex ut laboriosam aut voluptatem. Doloribus voluptatum dolores qui sapiente natus vero. Omnis quidem rerum sunt voluptatibus nisi. Nisi ratione facilis est iste.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (7, 'vkuphal@example.com', 'da077d6cbc6a947b5efee02c85a0fa70e6b35e1b', 'rippin.joanie', '13337', 'Deleniti enim perspiciatis quia asperiores. Quidem id et minima enim tenetur animi occaecati. Neque id nobis asperiores aut.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (8, 'melisa57@example.org', '06fcd4cbdc0c5744dd2a13a32a7c14bbc4bb7222', 'kelton.dickinson', '52527', 'Quibusdam doloremque qui culpa nihil voluptatem id. Sit quia sed reprehenderit vitae vel ut. Rem autem omnis sed. Sit aut aspernatur vel doloribus.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (9, 'eli.pfeffer@example.net', '8e2de3febc603cc7e286b15410f18bd27f9f399b', 'mariela.quitzon', '91001', 'Ut quo voluptatibus illum molestias quo itaque voluptas est. Vel explicabo eos necessitatibus odio. Eum quos provident mollitia nihil exercitationem omnis.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (10, 'simone45@example.com', '2c62fe59d4c930601f11755c8166377893eda5ba', 'rodrigo.wisoky', '26634', 'Recusandae provident quasi impedit ut quam autem sed. Quia accusantium aliquid numquam quia aperiam et iure. Perferendis voluptas fugit vero et autem aspernatur natus.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (11, 'kuhic.kayleigh@example.org', 'f358d49fca174ab8803b6f7b3bd137546edcb74e', 'scottie77', '00125', 'Cumque unde non voluptas adipisci veniam laboriosam mollitia. Dolorem illum asperiores praesentium. Porro ratione maiores quasi et consequatur debitis. Sequi at voluptatem itaque eius.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (12, 'rquigley@example.com', 'b38e378d631dbf440f625e4f59aa9d564ea2bc7e', 'hugh.windler', '74191', 'Aspernatur qui ut id odit eos. Minima eos nihil magni autem. Autem a aperiam nulla sapiente rerum.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (13, 'gutkowski.neva@example.org', 'f196b98fa2f2a5a369f7b302d5a61f26b5f62226', 'reyna.hane', '73718', 'Numquam et et dolor dolores minus natus. Praesentium dolor impedit quidem dignissimos ut id quia.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (14, 'hudson.sister@example.com', '03376acebd449a829e79bbdcbbeb07fc4900ff26', 'nschmitt', '52413', 'Numquam et eos quibusdam et est. Sit ducimus dolores sunt sit qui quos vitae numquam. Provident molestiae quidem quis nisi.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (15, 'christine.d\'amore@example.com', 'f3c4fc7a65475c49509118aa0304e246bc0e699b', 'rollin86', '31257', 'Blanditiis voluptatem eligendi sunt praesentium sit soluta sed. Sapiente quo est rerum quos autem. Et delectus alias ab et voluptatem repellat et. Quibusdam ex et voluptates sed qui itaque et minima.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (16, 'smayer@example.org', 'c029e8558d88d3cc2865622aec7ae6a191616dee', 'berry.lueilwitz', '50555', 'Ipsam commodi earum ut assumenda. Quia commodi deleniti eaque natus ducimus molestias aperiam.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (17, 'icie34@example.net', '29019d2a2ddb1869d543c9697ce146916bf17629', 'lyla12', '31388', 'Architecto ipsa dignissimos eligendi dolore deleniti repellat. Quia ad in pariatur. Qui qui et ipsa nisi ullam repellendus.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (18, 'burdette23@example.com', 'e8d4f6f00ccda04f4eb00586f913601dd9bf6c08', 'trycia.stiedemann', '71841', 'Id eum alias veniam vitae ab. Et rem omnis debitis tenetur delectus voluptatem omnis. Velit deserunt autem reiciendis dolor sit sunt suscipit. Sapiente sit vel quae consequuntur.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (19, 'madge12@example.org', '3690beaff959ef79e2a7cf0c01c1e3acdde89bbb', 'glegros', '16711', 'Molestiae ut provident quae aut sed. Corporis autem soluta in velit ducimus unde. Corrupti eius quis voluptatum velit. Ea assumenda eaque delectus illo fugit facere.', 'http://lorempixel.com/640/480/');
INSERT INTO `user` (`user_id`, `email`, `password`, `username`, `location`, `bio`, `user_photo`) VALUES (20, 'beier.logan@example.org', '87608a7fb2f4a33b5b125efdf306e5831250fb2b', 'rogers77', '88147', 'Et quia quam vero adipisci ad. Architecto quis eligendi veniam quaerat ut ipsum. Laborum voluptate dolorem perspiciatis id ut et id accusantium. Et delectus quia quia minus voluptate.', 'http://lorempixel.com/640/480/');


